baseurl = "https://bloatedloafyt.github.io"
languageCode = "en-us"
title = "Welcome to bloatedloaf's site!"
theme = "hugo-theme-hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "A simple theme for Hugo"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"themes\"hellofriend\" 
